container:
    image: python:3.5-slim

code_check_task:
    pip_cache:
        folder: ~/.cache/pip
        populate_script: pip install pylint requests yapf
    pip_install_script: pip install pylint requests yapf
    buildkit_script:
        - python3 -m yapf --style '.style.yapf' -e '*/third_party/*' -rpd buildkit
        - ./devutils/pylint_buildkit.py --hide-fixme
    devutils_script:
        - python3 -m yapf --style '.style.yapf' -rpd devutils
        - ./devutils/pylint_devutils.py --hide-fixme devutils
    get_package_script:
        - python3 -m yapf --style '.style.yapf' -pd get_package.py
        - ./devutils/pylint_devutils.py --hide-fixme get_package.py
    run_buildkit_cli_script:
        - python3 -m yapf --style '.style.yapf' -pd run_buildkit_cli.py
        - ./devutils/pylint_devutils.py --hide-fixme run_buildkit_cli.py

validate_config_task:
    validate_config_script: ./devutils/validate_config.py

validate_patches_task:
    pip_cache:
        folder: ~/.cache/pip
        populate_script: pip install requests
    pip_install_script: pip install requests
    validate_patches_script:
        - ./devutils/validate_patches.py -r
